//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class Buttonhighlight_mat
    {
        public const string BundleName = "buttonhighlight_mat";
        public const string BUTTONHIGHLIGHT = "buttonhighlight";
    }
    public class Buttonhighlight_shader
    {
        public const string BundleName = "buttonhighlight_shader";
        public const string BUTTONHIGHLIGHT = "buttonhighlight";
    }
}
